### PR TITLE
Seeds

### LINKED ISSUE #54: Create Seed Data
- [ ] User table (add new column info)

- [ ] Product History Table

- [ ] Subscriptions Table (add new column info)

- [ ] Crates table (may not need new data)

- [ ] Crate Products table

- [ ] Products table (may not need new data)

### PR DESCRIPTION
**Pull request by AngelaGuardia**
#### What does this PR do?
It creates seeder files to populate the following tables:
- Users (including new fields like description, image, and address)
- Subscriptions (each user is subscribed to two crates)
- CrateProducts (each crate has products that match its description i.e. men's clothes has men's shirts etc.)
- ProductsHistory (each user gets from 4 to 6 products and keeps all but 1 or two)

#### Where should the reviewer start?
Start in the seeders folder `code/api/src/seeders` there you will find 4 new files for the new seeds

#### How should this be manually tested?
- Open up the database in postico (most of these tables should be empty)
- Run `./node_modules/.bin/sequelize db:seed:all` within the API directory
- You should be able to see data in the tables 

#### Any background context you want to provide?
N/A

#### What are the relevant tickets?
closes #54 

#### Screenshots (if appropriate)
N/A

#### Questions:
For the subscriptions next delivery date I tried a couple of ways of making the delivery date something other than today but was unable to make it work:
- I tried creating a `var today = new Date();` and then within the nextDeliveryDate field using `today.add(1).day()` but got and error: `today.add is not a function`
- I tried `import moment from moment` to mimic some of the functionality I saw being used in the FE but for the following error: `cannot use import outside a module`

I don't think this needs to be changed but would love to hear some ideas on how we could make it work

#### New Feature Submissions:
 * Have you added an explanation of what your changes do? YES
 * Have you linted your code locally prior to submission? YES

#### Testing:
 * Have you written new tests for your core changes, as applicable? N/A
 * Have you successfully ran tests with your changes locally? N/A
 * All new and existing tests passed? N/A

### CODE REVIEW

**Comment by BlakeDonn** [comment]
`I tried creating a var today = new Date(); and then within the nextDeliveryDate field using today.add(1).day() but got and error: today.add is not a function`

Yeah! So to add a specific date you can just have something like `let nextDelivery = new Date(2021, 00, 01)` which will output  `Fri Jan 01 2021 00:00:00 GMT-0500 (Eastern Standard Time)`

**Review by ckccameron — APPROVED** [review]
👍🏽 This PR looks good

**Review by BlakeDonn — APPROVED** [review]
Looks great, from what I can see we have all the information we need to have a functioning front-end. Just a note for some next steps, the `nextDeliveryDate` will require a small amount of logic to be added on the frontend to display on the users profile.

**Comment by AngelaGuardia** [comment]
> `I tried creating a var today = new Date(); and then within the nextDeliveryDate field using today.add(1).day() but got and error: today.add is not a function`
> 
> Yeah! So to add a specific date you can just have something like `let nextDelivery = new Date(2021, 00, 01)` which will output `Fri Jan 01 2021 00:00:00 GMT-0500 (Eastern Standard Time)`

Thanks @BlakeDonn!! I just noticed that I used `var` again instead of let or const!! StackOverflow keeps leading me astray haha

**Review by nicolegooden — APPROVED** [review]
This looks awesome! I'm excited to see the updates for each product's details - for example, the product name, description, style?, etc.

**Pull request merged**
